# Default values for pg-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: pg-service
nfsServer: 192.168.72.100
name: rabbitmq
replicaCount: 1
host: rabbitmq

image:
  repository: rabbitmq
  tag: latest
  pullPolicy: IfNotPresent

service:
  clusterIP: 10.98.55.210

resources: 
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

user: root
password: root
