# Default values for pg-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: pg-service
nfsServer: 192.168.72.100
examples:
  userDbMaster: 
    name: "user-db-master"
    host: "user.db.master"
    replicaCount: 1
    serverId: 1
    image:
      repository: mariadb
      tag: 10.7
      pullPolicy: IfNotPresent
    
    service:
      clusterIP: 10.98.55.100
      port: 3306

    resources: 
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
        
  userDbSlave1: 
    name: "user-db-slave1"
    host: "user.db.slave1"
    replicaCount: 1
    serverId: 2
    image:
      repository: mariadb
      tag: 10.7
      pullPolicy: IfNotPresent
    
    service:
      clusterIP: 10.98.55.101
      port: 3306

    resources: 
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi


mysqlDataBase: pg_user
mysqlUser: pg_user
mysqlPassword: pg_user
mysqlRootPassword: root

