{{- $namespace := .Values.namespace -}}
{{ $e3wName := .Values.e3w.name }}
{{- $examples := .Values.examples -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $e3wName }}-cm
  namespace: {{ $namespace }}
  labels:
    app: {{ $e3wName }}-cm
data:
  config.default.ini: |
    [app]
    port=8080
    auth=false

    [etcd]
    root_key=pg-service
    dir_value=
    addr={{- range $etcdkey, $etcdVal := $examples }}{{ $etcdVal.service.clusterIP }}:2379,{{-   end   }}
    username=
    password=
    cert_file=
    key_file=
    ca_file=


    