apiVersion: v1
kind: Service
metadata:
  name: user-db-master-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-db-master-service
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.userDbMaster.service.port }}
      targetPort: {{ .Values.userDbMaster.service.port }}
      protocol: TCP
  selector:
    app: user-db-master-pod
