apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: user-db
  namespace: {{ .Values.namespace }}
spec:
  rules:
{{- range $key, $val := .Values.examples }}
  - host: {{ $val.host }}
    http:
      paths:
      - path: 
        backend:
          serviceName: {{ $val.name }}-service
          servicePort: {{ $val.service.port }}
{{-   end   }}