# Default values for pg-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: pg-service
userDbMaster: 
  replicaCount: 1
  image:
    repository: mariadb
    tag: 10.7
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3306

  resources: 
    limits:
     cpu: 1
     memory: 1Gi
    requests:
     cpu: 100m
     memory: 128Mi

  mysqlDataBase: pg_user
  mysqlUser: pg_user
  mysqlPassword: pg_user
  mysqlRootPassword: root

