apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    max_connections = 600
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360


# apiVersion: v1
# data:
#   "3306": mysql/mysql-service:3306
# kind: ConfigMap
# metadata:
#   name: tcp-services
#   namespace: ingress-nginx