apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 3
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 300m
              memory: 400Mi
        #   volumeMounts:
        #     - name: mysql-storage
        #       mountPath: "/var/lib/mysql"
        #       subPath: "mysql" 
        #     - name: mysql-conf
        #       mountPath: /etc/mysql/conf.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.userDbMaster.mysqlRootPassword}}
    #   volumes:
    #     - name: mysql-storage
    #       persistentVolumeClaim:
    #         claimName: mysql-storage
    #     - name: mysql-conf
    #       persistentVolumeClaim:
    #         claimName: mysql-storage