apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-service
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  type: ClusterIP
  ports:
    - port: 9091
      name: rpc-port
      targetPort: 9091
      protocol: TCP
  selector:
    app: {{ .Values.name }}-pod

