// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/869413421/pg-service/user/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// PasswordRestRepositoryInterface is an autogenerated mock type for the PasswordRestRepositoryInterface type
type PasswordRestRepositoryInterface struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: email
func (_m *PasswordRestRepositoryInterface) GetByEmail(email string) (*model.PasswordReset, error) {
	ret := _m.Called(email)

	var r0 *model.PasswordReset
	if rf, ok := ret.Get(0).(func(string) *model.PasswordReset); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PasswordReset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByToken provides a mock function with given fields: token
func (_m *PasswordRestRepositoryInterface) GetByToken(token string) (*model.PasswordReset, error) {
	ret := _m.Called(token)

	var r0 *model.PasswordReset
	if rf, ok := ret.Get(0).(func(string) *model.PasswordReset); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PasswordReset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
