apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-service
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  type: ClusterIP
  ports:
    - port: 6831
      name: udp-port
      targetPort: 6831
      protocol: UDP
    - port: 16686
      name: http-port
      targetPort: 16686
      protocol: TCP
  selector:
    app: {{ .Values.name }}-pod

