apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.apiName }}-service
spec:
  clusterIP: {{ .Values.service.apiClusterIP }}
  type: ClusterIP
  ports:
    - port: 8080
      name: api-port
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.apiName }}-pod

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webName }}-service
spec:
  clusterIP: {{ .Values.service.webClusterIP }}
  type: ClusterIP
  ports:
    - port: 8082
      name: http-port
      targetPort: 8082
      protocol: TCP
  selector:
    app: {{ .Values.webName }}-pod

