{{- $namespace := .Values.namespace -}}
{{- $user := .Values.user -}}
{{- $password := .Values.password -}}
{{- $name := .Values.name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
  namespace: {{ $namespace }}
spec:
  # pod数量
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}-pod
  template:
    metadata:
      labels:
        app: {{ $name }}-pod
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # 镜像拉取策略
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ $name }}
          # 设置主机变量
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ $user }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ $password }}
          # 暴露容器端口
          ports:
            - name: tcp
              containerPort: 15672
              protocol: TCP
            - name: http
              containerPort: 5672
              protocol: TCP
          volumeMounts:
            - name: mq-storage
              mountPath: "/var/lib/rabbitmq"
              subPath: "rabbitmq" 
          # 资源限制
          resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
      # 声明挂载
      volumes:
        - name: mq-storage
          persistentVolumeClaim:
            claimName: {{ $name }}-pvc
            readOnly: false


